### PR TITLE
see the detail

### PR DESCRIPTION
**Pull request by godcong**
1. change all id(s) to int64
2. rename Id(s) to ID(s)
3. add #cgo defined to tdlib.go for fix build error.
4. change path to ${SRCDIR} (optional) : relate:  tdlib.go,tdjson_dynamic.go
5. fix member_id int32 to MessageSender

this perhaps fixed:
https://github.com/zelenin/go-tdlib/issues/67
https://github.com/zelenin/go-tdlib/issues/61
https://github.com/zelenin/go-tdlib/issues/56

### CODE REVIEW

**Comment by AlessandroPomponio** [comment]
Thanks for the work you've done @godcong, it was really useful!

However now that I've updated to your version of the go-tdlib wrapper, I'm receiving the following error when using the method `SetChatMemberStatus`: `400 Message sender must be non-empty`

Code example:
```go
func BanUser(bannedUserID int64, chatID int64) error {

	_, err := tdlibClient.SetChatMemberStatus(&client.SetChatMemberStatusRequest{
		ChatID: chatID,
		UserID: bannedUserID,
		Status: &client.ChatMemberStatusBanned{BannedUntilDate: 0},
	})

	return err
}
```

Where `tdlibClient` is an instance of `*client.Client`
Are you by any chance seeing the same issue or is it something solely on my end?
Thanks again

**Comment by godcong** [comment]
I only used `SearchChatMembers` , this api is ok.
https://github.com/motomototv/telebot/blob/a9b63ba3cd315b799c6f676101aa5f87b28ad617/internal/client/client.go#L107

**Comment by AlessandroPomponio** [comment]
Hello @godcong 

I have worked out the issue and submitted a fix in your branch. Thanks once again for the work you've done. I do think we will have to ask @zelenin if he could update the wrapper to include the latest changes in the tdlib master branch. Unfortunately they've introduced **many** breaking changes that haven't been tagged in any version, making this wrapper quite broken.

**Comment by godcong** [comment]
v0.50 seems to have been fixed

**Pull request closed without merging**
